06-Fiap.Web.AspNet/Models/Condominio.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace _06_Fiap.Web.AspNet.Models
{
    [Table("T_ASP_CONDOMINIO")]
    public class Condominio
    {
        [Column("Id"), HiddenInput]
        public int CondominioId { get; set; }
        [Required, MaxLength(50)]
        public string Nome { get; set; }
        public int Blocos { get; set; }
        public bool Ativo { get; set; }
        public Tipo Tipo { get; set; }

        //Relacionamentos
        public Sindico Sindico { get; set; }
        public IList<Imovel> Imoveis { get; set; }
        public IList<CondominioConstrutora> CondominioConstrutoras { get; set; }

    }
}

06-Fiap.Web.AspNet/Controllers/CondominioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _06_Fiap.Web.AspNet.Models;
using _06_Fiap.Web.AspNet.Persistence;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _06_Fiap.Web.AspNet.Controllers
{
    public class CondominioController : Controller
    {
        private CondominioContext _context;


        public CondominioController(CondominioContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        //LISTAR
        [HttpGet]
        public IActionResult Listar()
        {
            //include -> inclui o relacionamento na pesquisa
            return View(_context.Condominios.Include(c => c.Sindico).ToList());
        }


        //CADASTRAR
        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Condominio condominio)
        {
            _context.Condominios.Add(condominio);
            _context.SaveChanges();
            TempData["mensagem"] = "CADASTRADO";
            return RedirectToAction("Listar");
        }


        //EDITAR
        [HttpGet]
        public IActionResult Editar(int id)
        {
            //include -> inclui o relacionamento na pesquisa
            var condominio = _context.Condominios.Include(c => c.Sindico)
                .Where(c => c.CondominioId == id).FirstOrDefault();
            return View(condominio);
        }

        [HttpPost]
        public IActionResult Editar(Condominio condominio)
        {
            _context.Condominios.Update(condominio);
            _context.SaveChanges();
            TempData["mensagem"] = "Editado com sucesso";

            return RedirectToAction("Listar");
        }

        //EXCLUIR
        [HttpPost]
        public IActionResult Excluir(int id)
        {
            //include -> inclui o relacionamento na pesquisa
            var condominio = _context.Condominios.Find(id);
            _context.Condominios.Remove(condominio);
            _context.SaveChanges();
            TempData["mensagem"] = "Excluido";
            return RedirectToAction("Listar");
        }

        //PESQUISAR
        [HttpGet]
        public IActionResult Pesquisar(string termoPesquisa)
        {
            //include -> inclui o relacionamento na pesquisa
            var lista = _context.Condominios.Where(
                churros => churros.Nome.Contains(termoPesquisa))
                .Include(c => c.Sindico).ToList();
            return View("Listar",lista);
        }    

        //BUSCAR

    }
}

06-Fiap.Web.AspNet/Controllers/ImovelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _06_Fiap.Web.AspNet.Models;
using _06_Fiap.Web.AspNet.Persistence;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace _06_Fiap.Web.AspNet.Controllers
{
    public class ImovelController : Controller
    {
        private CondominioContext _context;

        public ImovelController(CondominioContext context)
        {
            _context = context;
        }
        private void CarregarSelectCondominio()
        {
            var condominios = _context.Condominios.ToList();
            ViewBag.condominios = new SelectList(condominios, "CondominioId", "Nome");
        }

        //CADASTRAR
        [HttpGet]
        public IActionResult Cadastrar()
        {
            var condominios = _context.Condominios.ToList();
            ViewBag.condominios = new SelectList(condominios, "CondominioId", "Nome");
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Imovel imovel)
        {
            _context.Add(imovel);
            _context.SaveChanges();
            return RedirectToAction("Listar");
        }


        //LISTAR
        [HttpGet]
        public IActionResult Listar(int termoBusca)
        {
            CarregarSelectCondominio();
            return View(_context.Imoveis.Include(c => c.Condominio)
                    .Where(i => i.CondominioId == termoBusca || termoBusca == 0).ToList());
        }

        //EDITAR
        [HttpGet]
        public IActionResult Editar(int id)
        {
            CarregarSelectCondominio();

            var imovel = _context.Imoveis.Include(c => c.Condominio)
                .Where(i => i.ImovelId == id ).FirstOrDefault();
            return View(imovel);
        }


        [HttpPost]
        public IActionResult Editar(Imovel imovel)
        {
            _context.Imoveis.Update(imovel);
            _context.SaveChanges();
            TempData["mensagem"] = "Editado com sucesso";
            return RedirectToAction("Listar");
        }

        //EXCLUIR
        [HttpPost]
        public IActionResult Excluir(int id)
        {
            var imovel = _context.Imoveis.Find(id);
            _context.Imoveis.Remove(imovel);
            _context.SaveChanges();
            TempData["mensagem"] = "Excluido";
            return RedirectToAction("Listar");

        }
      
       
    }
}

06-Fiap.Web.AspNet/Views/Condominio/Cadastrar.cshtml
@model Condominio
@{
    ViewData["Title"] = "Cadastrar";
}

<h1>Cadastrar</h1>

<mensagem texto="@TempData["mensagem"]"></mensagem>

<form asp-action="Cadastrar">
    <partial name="_formulario"/>
    <botao texto="Cadastrar"/>
</form>

06-Fiap.Web.AspNet/Views/Condominio/Editar.cshtml
@model Condominio
@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<form asp-action="Editar" asp-controller="Condominio">
    <input asp-for="CondominioId" />
    <partial name="_formulario" />
    <botao texto="Editar" />
</form>

06-Fiap.Web.AspNet/Views/Condominio/Listar.cshtml
@model List<Condominio>

@{
    ViewData["Title"] = "Listar";
}

<h1>Listar</h1>

<mensagem texto="@TempData["mensagem"]"></mensagem>

<form asp-action="Pesquisar" method="get" class="form-inline">
    <input type="text" name="termoPesquisa" class="form-control" />       
    <input type="submit" value="Buscar" class="ml-2 btn btn-success" />
</form>
<br />

<table class="table table-bordered">
    <tr>
        
        <th>Nome</th>
        <th>Blocos</th>
        <th>Tipo</th>
        <th>Ativo</th>
        <th>Nome do Sindico</th>
        <th>Email do Sindico</th>
        <th>Opções</th>
    </tr>
    @foreach (var itens in Model)
    {
<tr>
   
    <td>@itens.Nome</td>
    <td>@itens.Blocos</td>
    <td>@itens.Tipo</td>
    <td>@(itens.Ativo ? "Sim" : "Não")</td>
    <td>@itens.Sindico.Nome</td>
    <td>@itens.Sindico.Email</td>
    <td>
        <a class="btn btn-sm btn-light" asp-action="Editar" asp-route-id="@itens.CondominioId">Editar</a>
        <!-- Button trigger modal -->
        <button onclick="codigo.value = @itens.CondominioId" type="button" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#exampleModal">
            Excluir
        </button>
       <a asp-controller="Imovel" asp-action="Listar" class="btn btn-sm btn-light" asp-route-termoBusca="@itens.CondominioId">Imoveis</a>


    </td>
</tr>
    }

</table>




<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
               Deseja realmente excluir
            </div>
            <div class="modal-footer">
                <form asp-action="Excluir">
                    <input type="hidden" name="id" id="codigo"/>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-primary" >Sim</button>
                </form>
            </div>
        </div>
    </div>
</div>

06-Fiap.Web.AspNet/Views/Condominio/_formulario.cshtml
@model Condominio

<div class="form-group">
    <label asp-for="Nome"> </label>
    <input asp-for="Nome" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Blocos"> </label>
    <input asp-for="Blocos" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Tipo"> </label>
    <select asp-for="Tipo" asp-items="@Html.GetEnumSelectList<Tipo>()" class="form-control">
        <option>Selecione</option>
    </select>
</div>
<div class="form-group">
    <input asp-for="Ativo" />
    <label asp-for="Ativo"> </label>
</div>
<fieldset>
    <legend>Sindico</legend>
    <div class="form-group">
        <label asp-for="Sindico.Nome"> </label>
        <input asp-for="Sindico.Nome" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Sindico.Email"> </label>
        <input asp-for="Sindico.Email" class="form-control" />
    </div>
</fieldset>