05-Fiap.Web.AspNet/Models/Diretor.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace _05_Fiap.Web.AspNet.Models
{
    [Table("T_ASP_DIRETOR")]
    public class Diretor
    {
        [Column("Id"),HiddenInput]
        public int DiretorId { get; set; }
        [Required,MaxLength(50)]
        public string Nome{ get; set; }
        [Display(Name = "Data de Nascimento"), Required, DataType(DataType.Date)]
        public DateTime DataNascimento { get; set; }
        public Sexo Genero { get; set; }
    }
}

05-Fiap.Web.AspNet/Models/ErrorViewModel.cs
using System;

namespace _05_Fiap.Web.AspNet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

05-Fiap.Web.AspNet/Models/Genero.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _05_Fiap.Web.AspNet.Models
{
    public enum Genero
    {
        Terror, Comedia, Aventura
    }
}

05-Fiap.Web.AspNet/Models/Serie.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace _05_Fiap.Web.AspNet.Models
{
    [Table("T_ASP_SERIE")]
    public class Serie
    {
        [Column("Id"), HiddenInput]
        public int SerieId { get; set; }

        [Required, MaxLength(50)]
        public string Nome { get; set; }
        public Genero Tipo { get; set; }
        [Display(Name = "Data Lançamento"), Required, DataType(DataType.Date)]
        public DateTime DataLancamento { get; set; }
        public int Temporadas { get; set; }

    }
}

05-Fiap.Web.AspNet/Models/Sexo.cs
namespace _05_Fiap.Web.AspNet.Models
{
    public enum Sexo
    {
        Masculino, Feminino, Outros
    }
}

05-Fiap.Web.AspNet/Controllers/DiretorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _05_Fiap.Web.AspNet.Models;
using _05_Fiap.Web.AspNet.Persistence;
using Microsoft.AspNetCore.Mvc;

namespace _05_Fiap.Web.AspNet.Controllers
{
    public class DiretorController : Controller
    {
        private BancoContext _context;

        public IActionResult Cadastrar(Diretor diretor)
        {
            return View();
        }
    }
}

05-Fiap.Web.AspNet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using _05_Fiap.Web.AspNet.Models;

namespace _05_Fiap.Web.AspNet.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

05-Fiap.Web.AspNet/Controllers/SerieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _05_Fiap.Web.AspNet.Models;
using _05_Fiap.Web.AspNet.Persistence;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _05_Fiap.Web.AspNet.Controllers
{
    public class SerieController : Controller
    {
        //tipo o "em", vai acessar as coisas no banco
        private BancoContext _context;


        //O Context será instanciado pelo framework
        public SerieController(BancoContext context)
        {
            _context = context;
        }

        //EXCLUIR -------------------------------------------------------
        [HttpPost]
        public IActionResult Excluir(int id)        {
            var serie = _context.Series.Find(id);
            _context.Remove(serie);
            _context.SaveChanges();
            TempData["msg"] = "Excluido !!";
            return RedirectToAction("Listar");
        }

        //EDITAR ---------------------------------------------------------
        [HttpPost]
        public IActionResult Editar(Serie serie)
        {
            //atualiza no banco
            _context.Attach(serie).State = EntityState.Modified;
            _context.SaveChanges();
            //Mensagem de suecesso para tela
            TempData["msg"] = "Atualizado";
            //Redirect para o método de listagem 
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            var serie = _context.Series.Find(id);
            return View(serie);
        }

        //LISTAR --------------------------------------------------------
        [HttpGet]
        public IActionResult Listar()
        {
            return View(_context.Series.ToList());
        }

        //CADASTRAR -----------------------------------------------------
        [HttpPost]
        public IActionResult Cadastrar(Serie serie)
        {
            _context.Series.Add(serie);
            _context.SaveChanges();
            TempData["msg"] = "Cadastrado";
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }
    }
}

05-Fiap.Web.AspNet/Views/Serie/Cadastrar.cshtml
@model Serie 

@{
    ViewData["Title"] = "Cadastrar";
}

<h1>Cadastrar</h1>


<form asp-action="Cadastrar" asp-controller="Serie" >
    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Tipo"></label>
        <select asp-for="Tipo" asp-items="@Html.GetEnumSelectList<Genero>()" class="form-control">
            <option>Selecione</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="DataLancamento"></label>
        <input asp-for="DataLancamento" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Temporadas"></label>
        <input asp-for="Temporadas" class="form-control" />
    </div>
    <botao></botao>
    @*<input type="submit" value="Cadastrar" class="btn btn-primary" />*@
</form>

05-Fiap.Web.AspNet/Views/Serie/Editar.cshtml
@model Serie

@{
    ViewData["Title"] = "Cadastrar";
}

<h1>Editar</h1>


<form asp-action="editar" asp-controller="Serie">
    <input asp-for="SerieId" />
        <partial name="_formulario" />
    <botao texto="Editar"/>
       <a asp-action="Listar"  class="btn btn-light">Cancelar</a>
 </form>

05-Fiap.Web.AspNet/Views/Serie/Listar.cshtml
@model IList<Serie>

@{
    ViewData["Title"] = "Listar";
}

<h1>Lista</h1>

<mensagem texto="@TempData["msg"]"></mensagem>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Gênero</th>
        <th>Data Lançamento</th>
        <th>Temporadas</th>
        <th>Opções</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.Tipo</td>
            <td>@item.DataLancamento.ToShortDateString()</td>
            <td>@item.Temporadas</td>
            <td><a class="btn btn-sm btn-light"asp-action="editar" asp-route-id="@item.SerieId">Editar</a>
                <button onclick="codigo.value = @item.SerieId" type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modalExemplo">
                    Excluir
                </button>
            </td>
        </tr>
    }
</table>



<!-- Modal -->
<div class="modal fade" id="modalExemplo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Excluir serie</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Você deseja realmente exlcuir a serie ?
      </div>
      <div class="modal-footer">
          <form asp-action="Excluir">
              <input type="hidden" name="id" id="codigo" />
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
              <button type="submit" class="btn btn-danger">Confirmar</button>
          </form>
      </div>
    </div>
  </div>
</div>

05-Fiap.Web.AspNet/Views/Serie/_formulario.cshtml
@model Serie

<div class="form-group">
    <label asp-for="Nome"></label>
    <input asp-for="Nome" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Tipo"></label>
    <select asp-for="Tipo" asp-items="@Html.GetEnumSelectList<Genero>()" class="form-control">
        <option>Selecione</option>
    </select>
</div>
<div class="form-group">
    <label asp-for="DataLancamento"></label>
    <input asp-for="DataLancamento" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Temporadas"></label>
    <input asp-for="Temporadas" class="form-control" />
</div>

05-Fiap.Web.AspNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _05_Fiap.Web.AspNet</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FIAP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Serie" asp-action="Cadastrar">Cadastrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Serie" asp-action="Listar">Listar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - _05_Fiap.Web.AspNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>