07-Fiap.Web.AspNet/Models/Cela.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace _07_Fiap.Web.AspNet.Models
{
    public class Cela
    {
        public int CelaId { get; set; }
        [Required,StringLength(30)]
        public string Nome { get; set; }
        public float Area { get; set; }
        public int QuantidadeMaxima { get; set; }
        public IList<Presidiario> Presidiarios { get; set; }
    }
}

07-Fiap.Web.AspNet/Models/ErrorViewModel.cs
using System;

namespace _07_Fiap.Web.AspNet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

07-Fiap.Web.AspNet/Models/NivelEscolaridade.cs
namespace _07_Fiap.Web.AspNet.Models
{
    public enum NivelEscolaridade
    {
        Primario, Medio, Superior, Mestrado, Doutorado
    }
}

07-Fiap.Web.AspNet/Models/Presidiario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace _07_Fiap.Web.AspNet.Models
{
    public class Presidiario
    {
        public int PresidiarioId { get; set; }

        [Required, StringLength(100)]
        public string Nome { get; set; }

        [Required, Display(Name = "Data de Entrada"), DataType(DataType.Date)]
        public DateTime DataEntrada { get; set; }

        [Display(Name = "Data de Saida"), DataType(DataType.Date)]
        public DateTime DataSaida { get; set; }

        [Display(Name = "Nivel de Escolaridade")]
        public NivelEscolaridade NivelEscolaridade { get; set; }

        public bool SaidaTemporaria { get; set; }

        public Cela Cela { get; set; }

        [Required]
        public int CelaId { get; set; }
    }
}

07-Fiap.Web.AspNet/ViewModels/DetalheCelaViewModel.cs
using _07_Fiap.Web.AspNet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _07_Fiap.Web.AspNet.ViewModels
{
    public class DetalheCelaViewModel
    {
        public Cela Cela { get; set; }
        public IList<Presidiario> Presidiarios { get; set; }
        public float Ocupacao { get; set; }
        public int QuantidadePresidiarios { get; set; }
    }
}

07-Fiap.Web.AspNet/Controllers/CelaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _07_Fiap.Web.AspNet.Models;
using _07_Fiap.Web.AspNet.Persistence;
using _07_Fiap.Web.AspNet.Repository;
using _07_Fiap.Web.AspNet.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace _07_Fiap.Web.AspNet.Controllers
{
    public class CelaController : Controller
    {
        private ICelaRepository _repository;
        private IPresidiarioRepository _presidiarioRepository;

        public CelaController(ICelaRepository repository, IPresidiarioRepository presidiarioRepository)
        {
            _repository = repository;
            _presidiarioRepository = presidiarioRepository;

        }

        //CADASTRO
        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Cela cela)
        {
            if (ModelState.IsValid)
            {
                _repository.Cadastrar(cela);
                _repository.Salvar();
                TempData["msg"] = "Cadastrada com Sucesso ";
                return RedirectToAction("Listar");
            }
            else
            {
                return View();
            }            
        }

        //LISTAR
        [HttpGet]
        public IActionResult Listar()
        {           
            return View(_repository.Listar());
        }

        //DETALHES
        [HttpGet]
        public IActionResult Detalhar(int codigo)
        {
            //Pesquisar a cela
            var cela = _repository.BuscarPorCodigo(codigo);
            //Listar presidiarios da cela
            var presidiarios = _presidiarioRepository.BuscarPor(p => p.CelaId == codigo);
            //Objeto que possui todas informações da tela
            var viewModel = new DetalheCelaViewModel()
            {
                Cela = cela,
                Presidiarios = presidiarios,
                QuantidadePresidiarios = presidiarios.Count,
                Ocupacao = (presidiarios.Count * 100) / cela.QuantidadeMaxima

            };
            return View(viewModel);
        }

    }
}

07-Fiap.Web.AspNet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using _07_Fiap.Web.AspNet.Models;

namespace _07_Fiap.Web.AspNet.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

07-Fiap.Web.AspNet/Controllers/PresidiarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _07_Fiap.Web.AspNet.Models;
using _07_Fiap.Web.AspNet.Persistence;
using _07_Fiap.Web.AspNet.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace _07_Fiap.Web.AspNet.Controllers
{
    public class PresidiarioController : Controller
    {
        private IPresidiarioRepository _repository;
        private ICelaRepository _celaRepository;

        public PresidiarioController(IPresidiarioRepository repository, ICelaRepository celaRepository)
        {
            _repository = repository;
            _celaRepository = celaRepository;
        }
       

        //Cadastrar
        [HttpGet]
        public IActionResult Cadastrar()
        {
            var lista = _celaRepository.Listar();
            ViewBag.celas = new SelectList(lista, "CelaId", "Nome");
            return View();
          
        }

        private void CarregarCelas()
        {
            var lista = _celaRepository.Listar();
            ViewBag.celas = new SelectList(lista, "CelaId", "Nome");
        }

        [HttpPost]
        public IActionResult Cadastrar(Presidiario presidiario)
        {
            if (ModelState.IsValid)
            {
                _repository.Cadastrar(presidiario);
                _repository.Salvar();
                return RedirectToAction("Listar");
            }
            else
            {
                CarregarCelas();
                return View();
            }
            
        }
        

        //Listar
        [HttpGet]
        public IActionResult Listar()
        {            
            return View(_repository.Listar());
        }

        //Definir Saida
        [HttpPost]
        public IActionResult DefinirSaida(int codigo)
        {
             var presidiario = _repository.BuscarPorCodigo(codigo);
            presidiario.SaidaTemporaria = true;
            _repository.Atualizar(presidiario);
            _repository.Salvar();
            return RedirectToAction("Detalhar","Cela", new { codigo = presidiario.CelaId});
        }
    }
}

07-Fiap.Web.AspNet/Views/Cela/Cadastrar.cshtml
@model Cela
@section scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}
@{
    ViewData["Title"] = "Cadastrar";
}
<h1>Cadastrar</h1>
@TempData["msg"]
<form asp-action="Cadastrar">
    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Area"></label>
        <input asp-for="Area" class="form-control">
        <span asp-validation-for="Area" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="QuantidadeMaxima"></label>
        <input asp-for="QuantidadeMaxima" class="form-control">
        <span asp-validation-for="QuantidadeMaxima" class="text-danger"></span>
    </div>
    <botao texto="Cadastar"></botao>
</form>

07-Fiap.Web.AspNet/Views/Cela/Detalhar.cshtml
@model DetalheCelaViewModel
@{
    ViewData["Title"] = "Detalhar";
}

<h1>Detalhar</h1>

<p>Cela: <span class="text-danger">@Model.Cela.Nome</span></p>
<p>Capacidade: <span class="text-danger">@Model.Cela.QuantidadeMaxima</span> Quantidade atual: <span class="text-danger">@Model.QuantidadePresidiarios</span></p>
<p>Ocupação: <span class="text-danger">@Model.Ocupacao %</span></p>

<div class="row">
    @foreach (var item in Model.Presidiarios)
    {
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@item.Nome</h5>
                    <p class="card-text">Data de entrada: @item.DataEntrada</p>
                    <p class="card-text">Data de saída: @item.DataSaida</p>
                    <p class="card-text">Nivel escolaridade: @item.NivelEscolaridade</p>
                    <br />
                    <p class="card-text">Saida Temporaria: @(item.SaidaTemporaria ? "Sim" : "Não")</p>
                    
                    <p>
                       
                        <button onclick="codigo.value = @item.PresidiarioId" type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalExemplo">
                          Saida temporária
                        </button>
                    </p>
                </div>
            </div>
        </div>
    }
</div>


<!-- Botão para acionar modal -->


<!-- Modal -->
<div class="modal fade" id="modalExemplo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Saída Temporaria</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Deseja definir a saída temporária do meliante ?
            </div>
            <div class="modal-footer">
                <form asp-controller="Presidiario" asp-action="DefinirSaida">
                    <input type="hidden" id="codigo" name="codigo"/>                    
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-light">Sim</button>
                </form>
            </div>
        </div>
    </div>
</div>

07-Fiap.Web.AspNet/Views/Cela/Listar.cshtml
@model  IList<Cela>
@{
    ViewData["Title"] = "Listar";
}

<h1>Celas</h1>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Área</th>
        <th>Quantidade Maxima</th>
        <th>Opções</th>
    </tr>
    @foreach(var itens in Model)
    {
        <tr>
            <td>@itens.Nome</td>
            <td>@itens.Area</td>
            <td>@itens.QuantidadeMaxima</td>
            <td>
                <a asp-action="detalhar" 
                   asp-route-codigo="@itens.CelaId" class="btn btn-primary">
                    Detalhes
                </a>
            </td>
        </tr>
    }
</table>

07-Fiap.Web.AspNet/Views/Presidiario/Cadastrar.cshtml
@model Presidiario

@{
    ViewData["Title"] = "Cadastrar";
}

<h2>Cadastro de Presidiário</h2>

@TempData["msg"]

<form asp-action="Cadastrar">
    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DataEntrada"></label>
        <input asp-for="DataEntrada" class="form-control" />
        <span asp-validation-for="DataEntrada" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DataSaida"></label>
        <input asp-for="DataSaida" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="NivelEscolaridade"></label>
        <select asp-for="NivelEscolaridade" class="form-control"
                asp-items="@Html.GetEnumSelectList<NivelEscolaridade>()">
            <option>Selecione</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Cela"></label>
        <select asp-for="CelaId" class="form-control" asp-items="@ViewBag.celas">
            <option>Selecione</option>
        </select>
    </div>
    <input type="submit" value="Cadastrar" class="btn btn-success" />
</form>

07-Fiap.Web.AspNet/Views/Presidiario/Listar.cshtml
@model IList<Presidiario>
@{
    ViewData["Title"] = "Listar";
}

<h1>Presidiario</h1>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Data entrada</th>
        <th>Data saída</th>
        <th>Nivel escolaridade</th>
        <th>Saida temporaria</th>
        
    </tr>
    @foreach (var itens in Model)
    {
        <tr>
            <td>@itens.Nome</td>
            <td>@itens.DataEntrada</td>
            <td>@itens.DataSaida</td>
            <td>@itens.NivelEscolaridade</td>
            <td>@itens.SaidaTemporaria</td>           
        </tr>
    }
</table>

07-Fiap.Web.AspNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _07_Fiap.Web.AspNet</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FIAP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">
                
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Presidiario
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-action="cadastrar" asp-controller="presidiario">Cadastrar</a>
                        <a class="dropdown-item" asp-action="listar" asp-controller="presidiario">Listar</a>
                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Cela
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-action="cadastrar" asp-controller="Cela">Cadastrar</a>
                        <a class="dropdown-item" asp-action="listar" asp-controller="Cela">Listar</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - _07_Fiap.Web.AspNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>